//@version=6
indicator(shorttitle="BB__20", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
mult2 = input.float(1.0, minval=0.001, maxval=50, title="StdDev")
fillColorUp = input(defval=color.new(color.green, 80), title="EMA9 Above Basis Fill Color")
fillColorDown = input(defval=color.new(color.orange, 80), title="EMA9 Below Basis Fill Color")


ema9 = ta.ema(src, 9)
p_ema9 = plot(ema9, title="EMA", color=color.yellow,linestyle=plot.linestyle_dotted,linewidth = 2)
ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
dev = mult * ta.stdev(src, length)
dev2 = mult2 * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)
p_basis = plot(basis, "Basis", color=#FFA500, offset = offset,linestyle = plot.linestyle_dotted,linewidth = 2)
fillColor = ema9 > basis ? fillColorUp : fillColorDown
fill(p_ema9, p_basis, color=fillColor, title="EMA9-Basis Fill")
p1 = plot(upper, "Upper", color=color.rgb(161, 53, 211), offset = offset)
p2 = plot(lower, "Lower", color.rgb(161, 53, 211), offset = offset)
//fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
upper2 = basis + dev2
lower2 = basis - dev2

plot(upper2, "Upper", color=#FF0000, offset = offset)
plot(lower2, "Lower", color=#FF0000, offset = offset)




