//@version=6
indicator(shorttitle="BBSRI50", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)

f_ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

length = input.int(50, minval=1)
maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
src = input(close, title="Source")
mult = input.float(1.0, minval=0.001, maxval=50, title="StdDev")
mult2 = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)

basis = f_ma(src, length, maType)
dev = mult * ta.stdev(src, length)
dev2 = mult2 * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
upper2 = basis + dev2
lower2 = basis - dev2

plot(basis, "Basis", color=#00D9FF, offset = offset, style = plot.style_linebr)
p1 = plot(upper, "Upper1", color=#00D9FF, offset = offset)
p2 = plot(lower, "Lower2", color=#00D9FF, offset = offset)
//fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
plot(upper2, "Upper2", color=#00D9FF, linewidth=3, offset = offset)
plot(lower2, "Lower2", color=#00D9FF, linewidth=3, offset = offset)


